# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_lesson.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(470, 500))
        MainWindow.setMaximumSize(QtCore.QSize(470, 500))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 120, 225, 255), stop:0.5 rgba(0, 120, 225, 255), stop:1 rgba(40, 145, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lessonList = QtWidgets.QListWidget(self.centralwidget)
        self.lessonList.setEnabled(False)
        self.lessonList.setGeometry(QtCore.QRect(10, 80, 451, 421))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(41)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lessonList.setFont(font)
        self.lessonList.setStyleSheet("QListWidget {background-color: rgba(0, 0, 0, 0); color: rgba(255, 255, 255, 100);}\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QListWidget::item:selected\n"
"{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}")
        self.lessonList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lessonList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lessonList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lessonList.setObjectName("lessonList")
        self.chooseButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseButton.setGeometry(QtCore.QRect(20, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.chooseButton.setFont(font)
        self.chooseButton.setStyleSheet("QPushButton {background-color: rgba(0, 0, 0, 0); color: rgba(159, 208, 255, 255); border-radius: 20px; border-style: solid; border-color: rgba(159, 208, 255, 255); border-width: 2px;}\n"
"QPushButton::hover::!pressed {background-color: rgba(20, 25, 80, 0); color: rgba(255, 255, 255, 255); border-color: rgba(255, 255, 255, 255)}\n"
"QPushButton::pressed {background-color: rgba(255, 255, 255, 255)};")
        self.chooseButton.setCheckable(False)
        self.chooseButton.setChecked(False)
        self.chooseButton.setFlat(False)
        self.chooseButton.setObjectName("chooseButton")
        self.tagUS = QtWidgets.QCheckBox(self.centralwidget)
        self.tagUS.setGeometry(QtCore.QRect(150, 20, 70, 40))
        font = QtGui.QFont()
        font.setItalic(True)
        self.tagUS.setFont(font)
        self.tagUS.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 255);")
        self.tagUS.setIconSize(QtCore.QSize(16, 16))
        self.tagUS.setChecked(False)
        self.tagUS.setObjectName("tagUS")
        self.tagRU = QtWidgets.QCheckBox(self.centralwidget)
        self.tagRU.setGeometry(QtCore.QRect(248, 20, 80, 40))
        font = QtGui.QFont()
        font.setItalic(True)
        self.tagRU.setFont(font)
        self.tagRU.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 255);")
        self.tagRU.setObjectName("tagRU")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(350, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton {background-color: rgba(0, 0, 0, 0); color: rgba(159, 208, 255, 255); border-radius: 20px; border-style: solid; border-color: rgba(159, 208, 255, 255); border-width: 2px;}\n"
"QPushButton::hover::!pressed {background-color: rgba(20, 25, 80, 0); color: rgba(255, 255, 255, 255); border-color: rgba(255, 255, 255, 255)}\n"
"QPushButton::pressed {background-color: rgba(255, 255, 255, 255)};")
        self.addButton.setCheckable(False)
        self.addButton.setChecked(False)
        self.addButton.setFlat(False)
        self.addButton.setObjectName("addButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseButton.setText(_translate("MainWindow", "Choose"))
        self.tagUS.setText(_translate("MainWindow", "English"))
        self.tagRU.setText(_translate("MainWindow", "Русский"))
        self.addButton.setText(_translate("MainWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
