# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greeting.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 520)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 120, 225, 255), stop:0.5 rgba(0, 120, 225, 255), stop:1 rgba(40, 145, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonRU = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRU.setGeometry(QtCore.QRect(140, 80, 250, 131))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(64)
        self.buttonRU.setFont(font)
        self.buttonRU.setStyleSheet("QPushButton {background-color: rgba(0, 0, 0, 0); color: rgba(159, 208, 255, 255); border-radius: 20px; border-style: solid; border-color: rgba(159, 208, 255, 255); border-width: 3px;}\n"
"QPushButton::hover::!pressed {background-color: rgba(20, 25, 80, 0); color: rgba(255, 255, 255, 255); border-color: rgba(255, 255, 255, 255)}\n"
"QPushButton::pressed {background-color: rgba(255, 255, 255, 255)};")
        self.buttonRU.setObjectName("buttonRU")
        self.usernameField = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameField.setGeometry(QtCore.QRect(40, 220, 450, 70))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setItalic(True)
        self.usernameField.setFont(font)
        self.usernameField.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 255);\n"
"border-radius: 30px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;\n"
"qproperty-frame: false;")
        self.usernameField.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameField.setObjectName("usernameField")
        self.buttonUS = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUS.setGeometry(QtCore.QRect(140, 300, 250, 131))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(64)
        self.buttonUS.setFont(font)
        self.buttonUS.setStyleSheet("QPushButton {background-color: rgba(0, 0, 0, 0); color: rgba(159, 208, 255, 255); border-radius: 20px; border-style: solid; border-color: rgba(159, 208, 255, 255); border-width: 3px;}\n"
"QPushButton::hover::!pressed {background-color: rgba(20, 25, 80, 0); color: rgba(255, 255, 255, 255); border-color: rgba(255, 255, 255, 255)}\n"
"QPushButton::pressed {background-color: rgba(255, 255, 255, 255)};")
        self.buttonUS.setObjectName("buttonUS")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonRU.setText(_translate("MainWindow", "RU"))
        self.usernameField.setText(_translate("MainWindow", "Inepta"))
        self.buttonUS.setText(_translate("MainWindow", "US"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
