# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_lesson.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 120, 225, 255), stop:0.5 rgba(0, 120, 225, 255), stop:1 rgba(40, 145, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newLessonText = QtWidgets.QTextEdit(self.centralwidget)
        self.newLessonText.setGeometry(QtCore.QRect(20, 200, 761, 401))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(34)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.newLessonText.setFont(font)
        self.newLessonText.setStyleSheet("background-color: rgba(0, 0, 0, 0); color: rgba(255, 255, 255, 255); ")
        self.newLessonText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.newLessonText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.newLessonText.setLineWidth(2)
        self.newLessonText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.newLessonText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.newLessonText.setObjectName("newLessonText")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(660, 153, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("QPushButton {background-color: rgba(0, 0, 0, 0); color: rgba(159, 208, 255, 255); border-radius: 20px; border-style: solid; border-color: rgba(159, 208, 255, 255); border-width: 2px;}\n"
"QPushButton::hover::!pressed {background-color: rgba(20, 25, 80, 0); color: rgba(255, 255, 255, 255); border-color: rgba(255, 255, 255, 255)}\n"
"QPushButton::pressed {background-color: rgba(255, 255, 255, 255)};")
        self.createButton.setCheckable(False)
        self.createButton.setChecked(False)
        self.createButton.setFlat(False)
        self.createButton.setObjectName("createButton")
        self.lessonName = QtWidgets.QLineEdit(self.centralwidget)
        self.lessonName.setGeometry(QtCore.QRect(10, 50, 781, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setItalic(True)
        self.lessonName.setFont(font)
        self.lessonName.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(159, 208, 255, 255);")
        self.lessonName.setText("")
        self.lessonName.setAlignment(QtCore.Qt.AlignCenter)
        self.lessonName.setObjectName("lessonName")
        self.tagUS = QtWidgets.QCheckBox(self.centralwidget)
        self.tagUS.setGeometry(QtCore.QRect(20, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(20)
        font.setItalic(True)
        self.tagUS.setFont(font)
        self.tagUS.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 255);")
        self.tagUS.setIconSize(QtCore.QSize(16, 16))
        self.tagUS.setChecked(False)
        self.tagUS.setObjectName("tagUS")
        self.tagRU = QtWidgets.QCheckBox(self.centralwidget)
        self.tagRU.setGeometry(QtCore.QRect(150, 150, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(20)
        font.setItalic(True)
        self.tagRU.setFont(font)
        self.tagRU.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 255);")
        self.tagRU.setIconSize(QtCore.QSize(16, 16))
        self.tagRU.setChecked(False)
        self.tagRU.setObjectName("tagRU")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newLessonText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica Neue\'; font-size:34pt; font-weight:400; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.tagUS.setText(_translate("MainWindow", "English"))
        self.tagRU.setText(_translate("MainWindow", "Русский"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
