# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1620, 997)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1200))
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        MainWindow.setBaseSize(QtCore.QSize(1680, 1050))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 140, 255, 255), stop:0.5 rgba(0, 140, 255, 255), stop:1 rgba(40, 145, 255, 255));\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.keyQ = QtWidgets.QLabel(self.centralwidget)
        self.keyQ.setEnabled(True)
        self.keyQ.setGeometry(QtCore.QRect(359, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyQ.sizePolicy().hasHeightForWidth())
        self.keyQ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyQ.setFont(font)
        self.keyQ.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyQ.setMouseTracking(True)
        self.keyQ.setAutoFillBackground(False)
        self.keyQ.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyQ.setFrameShape(QtWidgets.QFrame.Box)
        self.keyQ.setLineWidth(4)
        self.keyQ.setTextFormat(QtCore.Qt.AutoText)
        self.keyQ.setScaledContents(True)
        self.keyQ.setAlignment(QtCore.Qt.AlignCenter)
        self.keyQ.setObjectName("keyQ")
        self.keyW = QtWidgets.QLabel(self.centralwidget)
        self.keyW.setEnabled(True)
        self.keyW.setGeometry(QtCore.QRect(443, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyW.sizePolicy().hasHeightForWidth())
        self.keyW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyW.setFont(font)
        self.keyW.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyW.setMouseTracking(True)
        self.keyW.setAutoFillBackground(False)
        self.keyW.setStyleSheet("background-color: rgba(133, 225, 251, 255); color: rgba(109, 132, 139, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(109, 132, 139, 255);\n"
"border-width: 4px;\n"
"")
        self.keyW.setFrameShape(QtWidgets.QFrame.Box)
        self.keyW.setLineWidth(4)
        self.keyW.setTextFormat(QtCore.Qt.AutoText)
        self.keyW.setScaledContents(True)
        self.keyW.setAlignment(QtCore.Qt.AlignCenter)
        self.keyW.setObjectName("keyW")
        self.keyE = QtWidgets.QLabel(self.centralwidget)
        self.keyE.setEnabled(True)
        self.keyE.setGeometry(QtCore.QRect(527, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyE.sizePolicy().hasHeightForWidth())
        self.keyE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyE.setFont(font)
        self.keyE.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyE.setMouseTracking(True)
        self.keyE.setAutoFillBackground(False)
        self.keyE.setStyleSheet("background-color: rgba(234, 163, 195, 255); color: rgba(135, 117, 125, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(135, 117, 125, 255);\n"
"border-width: 4px;\n"
"")
        self.keyE.setFrameShape(QtWidgets.QFrame.Box)
        self.keyE.setLineWidth(4)
        self.keyE.setTextFormat(QtCore.Qt.AutoText)
        self.keyE.setScaledContents(True)
        self.keyE.setAlignment(QtCore.Qt.AlignCenter)
        self.keyE.setObjectName("keyE")
        self.keyR = QtWidgets.QLabel(self.centralwidget)
        self.keyR.setEnabled(True)
        self.keyR.setGeometry(QtCore.QRect(611, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyR.sizePolicy().hasHeightForWidth())
        self.keyR.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyR.setFont(font)
        self.keyR.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyR.setMouseTracking(True)
        self.keyR.setAutoFillBackground(False)
        self.keyR.setStyleSheet("background-color: rgba(246, 193, 136, 255); color: rgba(138, 124, 110, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(138, 124, 110, 255);\n"
"border-width: 4px;\n"
"\n"
"")
        self.keyR.setFrameShape(QtWidgets.QFrame.Box)
        self.keyR.setLineWidth(4)
        self.keyR.setTextFormat(QtCore.Qt.AutoText)
        self.keyR.setScaledContents(True)
        self.keyR.setAlignment(QtCore.Qt.AlignCenter)
        self.keyR.setObjectName("keyR")
        self.keyT = QtWidgets.QLabel(self.centralwidget)
        self.keyT.setEnabled(True)
        self.keyT.setGeometry(QtCore.QRect(695, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyT.sizePolicy().hasHeightForWidth())
        self.keyT.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyT.setFont(font)
        self.keyT.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyT.setMouseTracking(True)
        self.keyT.setAutoFillBackground(False)
        self.keyT.setStyleSheet("background-color: rgba(246, 193, 136, 255); color: rgba(138, 124, 110, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(138, 124, 110, 255);\n"
"border-width: 4px;\n"
"\n"
"")
        self.keyT.setFrameShape(QtWidgets.QFrame.Box)
        self.keyT.setLineWidth(4)
        self.keyT.setTextFormat(QtCore.Qt.AutoText)
        self.keyT.setScaledContents(True)
        self.keyT.setAlignment(QtCore.Qt.AlignCenter)
        self.keyT.setObjectName("keyT")
        self.keyI = QtWidgets.QLabel(self.centralwidget)
        self.keyI.setEnabled(True)
        self.keyI.setGeometry(QtCore.QRect(947, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyI.sizePolicy().hasHeightForWidth())
        self.keyI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyI.setFont(font)
        self.keyI.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyI.setMouseTracking(True)
        self.keyI.setAutoFillBackground(False)
        self.keyI.setStyleSheet("background-color: rgba(234, 163, 195, 255); color: rgba(135, 117, 125, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(135, 117, 125, 255);\n"
"border-width: 4px;\n"
"")
        self.keyI.setFrameShape(QtWidgets.QFrame.Box)
        self.keyI.setLineWidth(4)
        self.keyI.setTextFormat(QtCore.Qt.AutoText)
        self.keyI.setScaledContents(True)
        self.keyI.setAlignment(QtCore.Qt.AlignCenter)
        self.keyI.setObjectName("keyI")
        self.keyU = QtWidgets.QLabel(self.centralwidget)
        self.keyU.setEnabled(True)
        self.keyU.setGeometry(QtCore.QRect(863, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyU.sizePolicy().hasHeightForWidth())
        self.keyU.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyU.setFont(font)
        self.keyU.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyU.setMouseTracking(True)
        self.keyU.setAutoFillBackground(False)
        self.keyU.setStyleSheet("background-color: rgba(253, 238, 142, 255); color: rgba(139, 136, 111, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 136, 111, 255);\n"
"border-width: 4px;\n"
"")
        self.keyU.setFrameShape(QtWidgets.QFrame.Box)
        self.keyU.setLineWidth(4)
        self.keyU.setTextFormat(QtCore.Qt.AutoText)
        self.keyU.setScaledContents(True)
        self.keyU.setAlignment(QtCore.Qt.AlignCenter)
        self.keyU.setObjectName("keyU")
        self.keyY = QtWidgets.QLabel(self.centralwidget)
        self.keyY.setEnabled(True)
        self.keyY.setGeometry(QtCore.QRect(779, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyY.sizePolicy().hasHeightForWidth())
        self.keyY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyY.setFont(font)
        self.keyY.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyY.setMouseTracking(True)
        self.keyY.setAutoFillBackground(False)
        self.keyY.setStyleSheet("background-color: rgba(253, 238, 142, 255); color: rgba(139, 136, 111, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 136, 111, 255);\n"
"border-width: 4px;\n"
"")
        self.keyY.setFrameShape(QtWidgets.QFrame.Box)
        self.keyY.setLineWidth(4)
        self.keyY.setTextFormat(QtCore.Qt.AutoText)
        self.keyY.setScaledContents(True)
        self.keyY.setAlignment(QtCore.Qt.AlignCenter)
        self.keyY.setObjectName("keyY")
        self.keyO = QtWidgets.QLabel(self.centralwidget)
        self.keyO.setEnabled(True)
        self.keyO.setGeometry(QtCore.QRect(1031, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyO.sizePolicy().hasHeightForWidth())
        self.keyO.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyO.setFont(font)
        self.keyO.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyO.setMouseTracking(True)
        self.keyO.setAutoFillBackground(False)
        self.keyO.setStyleSheet("background-color: rgba(133, 225, 251, 255); color: rgba(109, 132, 139, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(109, 132, 139, 255);\n"
"border-width: 4px;\n"
"")
        self.keyO.setFrameShape(QtWidgets.QFrame.Box)
        self.keyO.setLineWidth(4)
        self.keyO.setTextFormat(QtCore.Qt.AutoText)
        self.keyO.setScaledContents(True)
        self.keyO.setAlignment(QtCore.Qt.AlignCenter)
        self.keyO.setObjectName("keyO")
        self.keyP = QtWidgets.QLabel(self.centralwidget)
        self.keyP.setEnabled(True)
        self.keyP.setGeometry(QtCore.QRect(1115, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyP.sizePolicy().hasHeightForWidth())
        self.keyP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyP.setFont(font)
        self.keyP.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyP.setMouseTracking(True)
        self.keyP.setAutoFillBackground(False)
        self.keyP.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyP.setFrameShape(QtWidgets.QFrame.Box)
        self.keyP.setLineWidth(4)
        self.keyP.setTextFormat(QtCore.Qt.AutoText)
        self.keyP.setScaledContents(True)
        self.keyP.setAlignment(QtCore.Qt.AlignCenter)
        self.keyP.setObjectName("keyP")
        self.keyK = QtWidgets.QLabel(self.centralwidget)
        self.keyK.setEnabled(True)
        self.keyK.setGeometry(QtCore.QRect(971, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyK.sizePolicy().hasHeightForWidth())
        self.keyK.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyK.setFont(font)
        self.keyK.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyK.setMouseTracking(True)
        self.keyK.setAutoFillBackground(False)
        self.keyK.setStyleSheet("background-color: rgba(234, 163, 195, 255); color: rgba(135, 117, 125, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(135, 117, 125, 255);\n"
"border-width: 4px;\n"
"")
        self.keyK.setFrameShape(QtWidgets.QFrame.Box)
        self.keyK.setLineWidth(4)
        self.keyK.setTextFormat(QtCore.Qt.AutoText)
        self.keyK.setScaledContents(True)
        self.keyK.setAlignment(QtCore.Qt.AlignCenter)
        self.keyK.setObjectName("keyK")
        self.keyH = QtWidgets.QLabel(self.centralwidget)
        self.keyH.setEnabled(True)
        self.keyH.setGeometry(QtCore.QRect(803, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyH.sizePolicy().hasHeightForWidth())
        self.keyH.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyH.setFont(font)
        self.keyH.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyH.setMouseTracking(True)
        self.keyH.setAutoFillBackground(False)
        self.keyH.setStyleSheet("background-color: rgba(253, 238, 142, 255); color: rgba(139, 136, 111, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 136, 111, 255);\n"
"border-width: 4px;\n"
"")
        self.keyH.setFrameShape(QtWidgets.QFrame.Box)
        self.keyH.setLineWidth(4)
        self.keyH.setTextFormat(QtCore.Qt.AutoText)
        self.keyH.setScaledContents(True)
        self.keyH.setAlignment(QtCore.Qt.AlignCenter)
        self.keyH.setObjectName("keyH")
        self.keyA = QtWidgets.QLabel(self.centralwidget)
        self.keyA.setEnabled(True)
        self.keyA.setGeometry(QtCore.QRect(383, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyA.sizePolicy().hasHeightForWidth())
        self.keyA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyA.setFont(font)
        self.keyA.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyA.setMouseTracking(True)
        self.keyA.setAutoFillBackground(False)
        self.keyA.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyA.setFrameShape(QtWidgets.QFrame.Box)
        self.keyA.setLineWidth(4)
        self.keyA.setTextFormat(QtCore.Qt.AutoText)
        self.keyA.setScaledContents(True)
        self.keyA.setAlignment(QtCore.Qt.AlignCenter)
        self.keyA.setObjectName("keyA")
        self.keyF = QtWidgets.QLabel(self.centralwidget)
        self.keyF.setEnabled(True)
        self.keyF.setGeometry(QtCore.QRect(635, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyF.sizePolicy().hasHeightForWidth())
        self.keyF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyF.setFont(font)
        self.keyF.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyF.setMouseTracking(True)
        self.keyF.setAutoFillBackground(False)
        self.keyF.setStyleSheet("background-color: rgba(246, 193, 136, 255); color: rgba(138, 124, 110, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(138, 124, 110, 255);\n"
"border-width: 4px;\n"
"\n"
"")
        self.keyF.setFrameShape(QtWidgets.QFrame.Box)
        self.keyF.setLineWidth(4)
        self.keyF.setTextFormat(QtCore.Qt.AutoText)
        self.keyF.setScaledContents(True)
        self.keyF.setAlignment(QtCore.Qt.AlignCenter)
        self.keyF.setObjectName("keyF")
        self.keyL = QtWidgets.QLabel(self.centralwidget)
        self.keyL.setEnabled(True)
        self.keyL.setGeometry(QtCore.QRect(1055, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyL.sizePolicy().hasHeightForWidth())
        self.keyL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyL.setFont(font)
        self.keyL.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyL.setMouseTracking(True)
        self.keyL.setAutoFillBackground(False)
        self.keyL.setStyleSheet("background-color: rgba(133, 225, 251, 255); color: rgba(109, 132, 139, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(109, 132, 139, 255);\n"
"border-width: 4px;\n"
"")
        self.keyL.setFrameShape(QtWidgets.QFrame.Box)
        self.keyL.setLineWidth(4)
        self.keyL.setTextFormat(QtCore.Qt.AutoText)
        self.keyL.setScaledContents(True)
        self.keyL.setAlignment(QtCore.Qt.AlignCenter)
        self.keyL.setObjectName("keyL")
        self.keyJ = QtWidgets.QLabel(self.centralwidget)
        self.keyJ.setEnabled(True)
        self.keyJ.setGeometry(QtCore.QRect(887, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyJ.sizePolicy().hasHeightForWidth())
        self.keyJ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyJ.setFont(font)
        self.keyJ.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyJ.setMouseTracking(True)
        self.keyJ.setAutoFillBackground(False)
        self.keyJ.setStyleSheet("background-color: rgba(253, 238, 142, 255); color: rgba(139, 136, 111, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 136, 111, 255);\n"
"border-width: 4px;\n"
"")
        self.keyJ.setFrameShape(QtWidgets.QFrame.Box)
        self.keyJ.setLineWidth(4)
        self.keyJ.setTextFormat(QtCore.Qt.AutoText)
        self.keyJ.setScaledContents(True)
        self.keyJ.setAlignment(QtCore.Qt.AlignCenter)
        self.keyJ.setObjectName("keyJ")
        self.keyD = QtWidgets.QLabel(self.centralwidget)
        self.keyD.setEnabled(True)
        self.keyD.setGeometry(QtCore.QRect(551, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyD.sizePolicy().hasHeightForWidth())
        self.keyD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyD.setFont(font)
        self.keyD.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyD.setMouseTracking(True)
        self.keyD.setAutoFillBackground(False)
        self.keyD.setStyleSheet("background-color: rgba(234, 163, 195, 255); color: rgba(135, 117, 125, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(135, 117, 125, 255);\n"
"border-width: 4px;\n"
"")
        self.keyD.setFrameShape(QtWidgets.QFrame.Box)
        self.keyD.setLineWidth(4)
        self.keyD.setTextFormat(QtCore.Qt.AutoText)
        self.keyD.setScaledContents(True)
        self.keyD.setAlignment(QtCore.Qt.AlignCenter)
        self.keyD.setObjectName("keyD")
        self.keyS = QtWidgets.QLabel(self.centralwidget)
        self.keyS.setEnabled(True)
        self.keyS.setGeometry(QtCore.QRect(467, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyS.sizePolicy().hasHeightForWidth())
        self.keyS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyS.setFont(font)
        self.keyS.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyS.setMouseTracking(True)
        self.keyS.setAutoFillBackground(False)
        self.keyS.setStyleSheet("background-color: rgba(133, 225, 251, 255); color: rgba(109, 132, 139, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(109, 132, 139, 255);\n"
"border-width: 4px;\n"
"")
        self.keyS.setFrameShape(QtWidgets.QFrame.Box)
        self.keyS.setLineWidth(4)
        self.keyS.setTextFormat(QtCore.Qt.AutoText)
        self.keyS.setScaledContents(True)
        self.keyS.setAlignment(QtCore.Qt.AlignCenter)
        self.keyS.setObjectName("keyS")
        self.keyG = QtWidgets.QLabel(self.centralwidget)
        self.keyG.setEnabled(True)
        self.keyG.setGeometry(QtCore.QRect(719, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyG.sizePolicy().hasHeightForWidth())
        self.keyG.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyG.setFont(font)
        self.keyG.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyG.setMouseTracking(True)
        self.keyG.setAutoFillBackground(False)
        self.keyG.setStyleSheet("background-color: rgba(246, 193, 136, 255); color: rgba(138, 124, 110, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(138, 124, 110, 255);\n"
"border-width: 4px;\n"
"\n"
"")
        self.keyG.setFrameShape(QtWidgets.QFrame.Box)
        self.keyG.setLineWidth(4)
        self.keyG.setTextFormat(QtCore.Qt.AutoText)
        self.keyG.setScaledContents(True)
        self.keyG.setAlignment(QtCore.Qt.AlignCenter)
        self.keyG.setObjectName("keyG")
        self.keyN = QtWidgets.QLabel(self.centralwidget)
        self.keyN.setEnabled(True)
        self.keyN.setGeometry(QtCore.QRect(843, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyN.sizePolicy().hasHeightForWidth())
        self.keyN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyN.setFont(font)
        self.keyN.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyN.setMouseTracking(True)
        self.keyN.setAutoFillBackground(False)
        self.keyN.setStyleSheet("background-color: rgba(253, 238, 142, 255); color: rgba(139, 136, 111, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 136, 111, 255);\n"
"border-width: 4px;\n"
"")
        self.keyN.setFrameShape(QtWidgets.QFrame.Box)
        self.keyN.setLineWidth(4)
        self.keyN.setTextFormat(QtCore.Qt.AutoText)
        self.keyN.setScaledContents(True)
        self.keyN.setAlignment(QtCore.Qt.AlignCenter)
        self.keyN.setObjectName("keyN")
        self.keyZ = QtWidgets.QLabel(self.centralwidget)
        self.keyZ.setEnabled(True)
        self.keyZ.setGeometry(QtCore.QRect(423, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyZ.sizePolicy().hasHeightForWidth())
        self.keyZ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyZ.setFont(font)
        self.keyZ.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyZ.setMouseTracking(True)
        self.keyZ.setAutoFillBackground(False)
        self.keyZ.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyZ.setFrameShape(QtWidgets.QFrame.Box)
        self.keyZ.setLineWidth(4)
        self.keyZ.setTextFormat(QtCore.Qt.AutoText)
        self.keyZ.setScaledContents(True)
        self.keyZ.setAlignment(QtCore.Qt.AlignCenter)
        self.keyZ.setObjectName("keyZ")
        self.keyV = QtWidgets.QLabel(self.centralwidget)
        self.keyV.setEnabled(True)
        self.keyV.setGeometry(QtCore.QRect(675, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyV.sizePolicy().hasHeightForWidth())
        self.keyV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyV.setFont(font)
        self.keyV.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyV.setMouseTracking(True)
        self.keyV.setAutoFillBackground(False)
        self.keyV.setStyleSheet("background-color: rgba(246, 193, 136, 255); color: rgba(138, 124, 110, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(138, 124, 110, 255);\n"
"border-width: 4px;\n"
"\n"
"")
        self.keyV.setFrameShape(QtWidgets.QFrame.Box)
        self.keyV.setLineWidth(4)
        self.keyV.setTextFormat(QtCore.Qt.AutoText)
        self.keyV.setScaledContents(True)
        self.keyV.setAlignment(QtCore.Qt.AlignCenter)
        self.keyV.setObjectName("keyV")
        self.keyM = QtWidgets.QLabel(self.centralwidget)
        self.keyM.setEnabled(True)
        self.keyM.setGeometry(QtCore.QRect(927, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyM.sizePolicy().hasHeightForWidth())
        self.keyM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyM.setFont(font)
        self.keyM.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyM.setMouseTracking(True)
        self.keyM.setAutoFillBackground(False)
        self.keyM.setStyleSheet("background-color: rgba(253, 238, 142, 255); color: rgba(139, 136, 111, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 136, 111, 255);\n"
"border-width: 4px;\n"
"")
        self.keyM.setFrameShape(QtWidgets.QFrame.Box)
        self.keyM.setLineWidth(4)
        self.keyM.setTextFormat(QtCore.Qt.AutoText)
        self.keyM.setScaledContents(True)
        self.keyM.setAlignment(QtCore.Qt.AlignCenter)
        self.keyM.setObjectName("keyM")
        self.keyC = QtWidgets.QLabel(self.centralwidget)
        self.keyC.setEnabled(True)
        self.keyC.setGeometry(QtCore.QRect(591, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyC.sizePolicy().hasHeightForWidth())
        self.keyC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyC.setFont(font)
        self.keyC.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyC.setMouseTracking(True)
        self.keyC.setAutoFillBackground(False)
        self.keyC.setStyleSheet("background-color: rgba(234, 163, 195, 255); color: rgba(135, 117, 125, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(135, 117, 125, 255);\n"
"border-width: 4px;\n"
"")
        self.keyC.setFrameShape(QtWidgets.QFrame.Box)
        self.keyC.setLineWidth(4)
        self.keyC.setTextFormat(QtCore.Qt.AutoText)
        self.keyC.setScaledContents(True)
        self.keyC.setAlignment(QtCore.Qt.AlignCenter)
        self.keyC.setObjectName("keyC")
        self.keyX = QtWidgets.QLabel(self.centralwidget)
        self.keyX.setEnabled(True)
        self.keyX.setGeometry(QtCore.QRect(507, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyX.sizePolicy().hasHeightForWidth())
        self.keyX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyX.setFont(font)
        self.keyX.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyX.setMouseTracking(True)
        self.keyX.setAutoFillBackground(False)
        self.keyX.setStyleSheet("background-color: rgba(133, 225, 251, 255); color: rgba(109, 132, 139, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(109, 132, 139, 255);\n"
"border-width: 4px;\n"
"")
        self.keyX.setFrameShape(QtWidgets.QFrame.Box)
        self.keyX.setLineWidth(4)
        self.keyX.setTextFormat(QtCore.Qt.AutoText)
        self.keyX.setScaledContents(True)
        self.keyX.setAlignment(QtCore.Qt.AlignCenter)
        self.keyX.setObjectName("keyX")
        self.keyB = QtWidgets.QLabel(self.centralwidget)
        self.keyB.setEnabled(True)
        self.keyB.setGeometry(QtCore.QRect(759, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyB.sizePolicy().hasHeightForWidth())
        self.keyB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyB.setFont(font)
        self.keyB.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyB.setMouseTracking(True)
        self.keyB.setAutoFillBackground(False)
        self.keyB.setStyleSheet("background-color: rgba(246, 193, 136, 255); color: rgba(138, 124, 110, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(138, 124, 110, 255);\n"
"border-width: 4px;\n"
"\n"
"")
        self.keyB.setFrameShape(QtWidgets.QFrame.Box)
        self.keyB.setLineWidth(4)
        self.keyB.setTextFormat(QtCore.Qt.AutoText)
        self.keyB.setScaledContents(True)
        self.keyB.setAlignment(QtCore.Qt.AlignCenter)
        self.keyB.setObjectName("keyB")
        self.keySpace = QtWidgets.QLabel(self.centralwidget)
        self.keySpace.setEnabled(True)
        self.keySpace.setGeometry(QtCore.QRect(591, 810, 416, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keySpace.sizePolicy().hasHeightForWidth())
        self.keySpace.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Silkscreen")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keySpace.setFont(font)
        self.keySpace.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keySpace.setMouseTracking(True)
        self.keySpace.setAutoFillBackground(False)
        self.keySpace.setStyleSheet("background-color: rgba(250, 250, 230, 255); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(139, 139, 134, 255);\n"
"border-width: 4px;")
        self.keySpace.setFrameShape(QtWidgets.QFrame.Box)
        self.keySpace.setLineWidth(4)
        self.keySpace.setText("")
        self.keySpace.setTextFormat(QtCore.Qt.AutoText)
        self.keySpace.setScaledContents(True)
        self.keySpace.setAlignment(QtCore.Qt.AlignCenter)
        self.keySpace.setObjectName("keySpace")
        self.stopwatch = QtWidgets.QLabel(self.centralwidget)
        self.stopwatch.setGeometry(QtCore.QRect(1150, 100, 400, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stopwatch.sizePolicy().hasHeightForWidth())
        self.stopwatch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.stopwatch.setFont(font)
        self.stopwatch.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stopwatch.setMouseTracking(True)
        self.stopwatch.setAutoFillBackground(False)
        self.stopwatch.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.stopwatch.setFrameShape(QtWidgets.QFrame.Box)
        self.stopwatch.setLineWidth(4)
        self.stopwatch.setTextFormat(QtCore.Qt.AutoText)
        self.stopwatch.setScaledContents(True)
        self.stopwatch.setAlignment(QtCore.Qt.AlignCenter)
        self.stopwatch.setObjectName("stopwatch")
        self.pause = QtWidgets.QLabel(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(1150, 100, 400, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pause.setFont(font)
        self.pause.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pause.setMouseTracking(True)
        self.pause.setAutoFillBackground(False)
        self.pause.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;\n"
"border-style: solid; border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.pause.setFrameShape(QtWidgets.QFrame.Box)
        self.pause.setLineWidth(4)
        self.pause.setTextFormat(QtCore.Qt.AutoText)
        self.pause.setScaledContents(True)
        self.pause.setAlignment(QtCore.Qt.AlignCenter)
        self.pause.setObjectName("pause")
        self.typingSpeed = QtWidgets.QLabel(self.centralwidget)
        self.typingSpeed.setGeometry(QtCore.QRect(640, 100, 400, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.typingSpeed.sizePolicy().hasHeightForWidth())
        self.typingSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.typingSpeed.setFont(font)
        self.typingSpeed.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.typingSpeed.setMouseTracking(True)
        self.typingSpeed.setAutoFillBackground(False)
        self.typingSpeed.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.typingSpeed.setFrameShape(QtWidgets.QFrame.Box)
        self.typingSpeed.setLineWidth(4)
        self.typingSpeed.setTextFormat(QtCore.Qt.AutoText)
        self.typingSpeed.setScaledContents(True)
        self.typingSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.typingSpeed.setObjectName("typingSpeed")
        self.insert = QtWidgets.QLabel(self.centralwidget)
        self.insert.setGeometry(QtCore.QRect(838, 442, 3, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.insert.sizePolicy().hasHeightForWidth())
        self.insert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.insert.setFont(font)
        self.insert.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.insert.setStyleSheet("background-color: rgba(255, 255, 255, 255); color: rgba(255, 255, 255, 255);\n"
"")
        self.insert.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.insert.setLineWidth(3)
        self.insert.setScaledContents(True)
        self.insert.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.insert.setObjectName("insert")
        self.mistakesMade = QtWidgets.QLabel(self.centralwidget)
        self.mistakesMade.setGeometry(QtCore.QRect(130, 100, 400, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mistakesMade.sizePolicy().hasHeightForWidth())
        self.mistakesMade.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.mistakesMade.setFont(font)
        self.mistakesMade.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.mistakesMade.setMouseTracking(True)
        self.mistakesMade.setAutoFillBackground(False)
        self.mistakesMade.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;\n"
"border-style: solid; border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.mistakesMade.setFrameShape(QtWidgets.QFrame.Box)
        self.mistakesMade.setLineWidth(4)
        self.mistakesMade.setTextFormat(QtCore.Qt.AutoText)
        self.mistakesMade.setScaledContents(True)
        self.mistakesMade.setAlignment(QtCore.Qt.AlignCenter)
        self.mistakesMade.setObjectName("mistakesMade")
        self.keyDot = QtWidgets.QLabel(self.centralwidget)
        self.keyDot.setEnabled(True)
        self.keyDot.setGeometry(QtCore.QRect(1095, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyDot.sizePolicy().hasHeightForWidth())
        self.keyDot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyDot.setFont(font)
        self.keyDot.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyDot.setMouseTracking(True)
        self.keyDot.setAutoFillBackground(False)
        self.keyDot.setStyleSheet("background-color: rgba(133, 225, 251, 255); color: rgba(109, 132, 139, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(109, 132, 139, 255);\n"
"border-width: 4px;\n"
"")
        self.keyDot.setFrameShape(QtWidgets.QFrame.Box)
        self.keyDot.setLineWidth(4)
        self.keyDot.setTextFormat(QtCore.Qt.AutoText)
        self.keyDot.setScaledContents(True)
        self.keyDot.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.keyDot.setObjectName("keyDot")
        self.keyComma = QtWidgets.QLabel(self.centralwidget)
        self.keyComma.setEnabled(True)
        self.keyComma.setGeometry(QtCore.QRect(1011, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyComma.sizePolicy().hasHeightForWidth())
        self.keyComma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyComma.setFont(font)
        self.keyComma.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyComma.setMouseTracking(True)
        self.keyComma.setAutoFillBackground(False)
        self.keyComma.setStyleSheet("background-color: rgba(234, 163, 195, 255); color: rgba(135, 117, 125, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(135, 117, 125, 255);\n"
"border-width: 4px;\n"
"")
        self.keyComma.setFrameShape(QtWidgets.QFrame.Box)
        self.keyComma.setLineWidth(4)
        self.keyComma.setTextFormat(QtCore.Qt.AutoText)
        self.keyComma.setScaledContents(True)
        self.keyComma.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.keyComma.setObjectName("keyComma")
        self.keySemicolon = QtWidgets.QLabel(self.centralwidget)
        self.keySemicolon.setEnabled(True)
        self.keySemicolon.setGeometry(QtCore.QRect(1139, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keySemicolon.sizePolicy().hasHeightForWidth())
        self.keySemicolon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keySemicolon.setFont(font)
        self.keySemicolon.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keySemicolon.setMouseTracking(True)
        self.keySemicolon.setAutoFillBackground(False)
        self.keySemicolon.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keySemicolon.setFrameShape(QtWidgets.QFrame.Box)
        self.keySemicolon.setLineWidth(4)
        self.keySemicolon.setTextFormat(QtCore.Qt.AutoText)
        self.keySemicolon.setScaledContents(True)
        self.keySemicolon.setAlignment(QtCore.Qt.AlignCenter)
        self.keySemicolon.setObjectName("keySemicolon")
        self.keyQuote = QtWidgets.QLabel(self.centralwidget)
        self.keyQuote.setEnabled(True)
        self.keyQuote.setGeometry(QtCore.QRect(1223, 642, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyQuote.sizePolicy().hasHeightForWidth())
        self.keyQuote.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyQuote.setFont(font)
        self.keyQuote.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyQuote.setMouseTracking(True)
        self.keyQuote.setAutoFillBackground(False)
        self.keyQuote.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyQuote.setFrameShape(QtWidgets.QFrame.Box)
        self.keyQuote.setLineWidth(4)
        self.keyQuote.setTextFormat(QtCore.Qt.AutoText)
        self.keyQuote.setScaledContents(True)
        self.keyQuote.setAlignment(QtCore.Qt.AlignCenter)
        self.keyQuote.setObjectName("keyQuote")
        self.keyLeftBracket = QtWidgets.QLabel(self.centralwidget)
        self.keyLeftBracket.setEnabled(True)
        self.keyLeftBracket.setGeometry(QtCore.QRect(1199, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyLeftBracket.sizePolicy().hasHeightForWidth())
        self.keyLeftBracket.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyLeftBracket.setFont(font)
        self.keyLeftBracket.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyLeftBracket.setMouseTracking(True)
        self.keyLeftBracket.setAutoFillBackground(False)
        self.keyLeftBracket.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyLeftBracket.setFrameShape(QtWidgets.QFrame.Box)
        self.keyLeftBracket.setLineWidth(4)
        self.keyLeftBracket.setTextFormat(QtCore.Qt.AutoText)
        self.keyLeftBracket.setScaledContents(True)
        self.keyLeftBracket.setAlignment(QtCore.Qt.AlignCenter)
        self.keyLeftBracket.setObjectName("keyLeftBracket")
        self.keyRightBracket = QtWidgets.QLabel(self.centralwidget)
        self.keyRightBracket.setEnabled(True)
        self.keyRightBracket.setGeometry(QtCore.QRect(1283, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyRightBracket.sizePolicy().hasHeightForWidth())
        self.keyRightBracket.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyRightBracket.setFont(font)
        self.keyRightBracket.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyRightBracket.setMouseTracking(True)
        self.keyRightBracket.setAutoFillBackground(False)
        self.keyRightBracket.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyRightBracket.setFrameShape(QtWidgets.QFrame.Box)
        self.keyRightBracket.setLineWidth(4)
        self.keyRightBracket.setTextFormat(QtCore.Qt.AutoText)
        self.keyRightBracket.setScaledContents(True)
        self.keyRightBracket.setAlignment(QtCore.Qt.AlignCenter)
        self.keyRightBracket.setObjectName("keyRightBracket")
        self.keyCaps = QtWidgets.QLabel(self.centralwidget)
        self.keyCaps.setEnabled(True)
        self.keyCaps.setGeometry(QtCore.QRect(235, 642, 144, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyCaps.sizePolicy().hasHeightForWidth())
        self.keyCaps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyCaps.setFont(font)
        self.keyCaps.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyCaps.setMouseTracking(True)
        self.keyCaps.setAutoFillBackground(False)
        self.keyCaps.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyCaps.setFrameShape(QtWidgets.QFrame.Box)
        self.keyCaps.setLineWidth(4)
        self.keyCaps.setTextFormat(QtCore.Qt.AutoText)
        self.keyCaps.setScaledContents(True)
        self.keyCaps.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.keyCaps.setObjectName("keyCaps")
        self.keyReturn = QtWidgets.QLabel(self.centralwidget)
        self.keyReturn.setEnabled(True)
        self.keyReturn.setGeometry(QtCore.QRect(1307, 642, 140, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyReturn.sizePolicy().hasHeightForWidth())
        self.keyReturn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyReturn.setFont(font)
        self.keyReturn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyReturn.setMouseTracking(True)
        self.keyReturn.setAutoFillBackground(False)
        self.keyReturn.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyReturn.setFrameShape(QtWidgets.QFrame.Box)
        self.keyReturn.setLineWidth(4)
        self.keyReturn.setTextFormat(QtCore.Qt.AutoText)
        self.keyReturn.setScaledContents(True)
        self.keyReturn.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.keyReturn.setObjectName("keyReturn")
        self.keySlash = QtWidgets.QLabel(self.centralwidget)
        self.keySlash.setEnabled(True)
        self.keySlash.setGeometry(QtCore.QRect(1179, 726, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keySlash.sizePolicy().hasHeightForWidth())
        self.keySlash.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keySlash.setFont(font)
        self.keySlash.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keySlash.setMouseTracking(True)
        self.keySlash.setAutoFillBackground(False)
        self.keySlash.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keySlash.setFrameShape(QtWidgets.QFrame.Box)
        self.keySlash.setLineWidth(4)
        self.keySlash.setTextFormat(QtCore.Qt.AutoText)
        self.keySlash.setScaledContents(True)
        self.keySlash.setAlignment(QtCore.Qt.AlignCenter)
        self.keySlash.setObjectName("keySlash")
        self.keyRightShift = QtWidgets.QLabel(self.centralwidget)
        self.keyRightShift.setEnabled(True)
        self.keyRightShift.setGeometry(QtCore.QRect(1263, 726, 184, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyRightShift.sizePolicy().hasHeightForWidth())
        self.keyRightShift.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyRightShift.setFont(font)
        self.keyRightShift.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyRightShift.setMouseTracking(True)
        self.keyRightShift.setAutoFillBackground(False)
        self.keyRightShift.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyRightShift.setFrameShape(QtWidgets.QFrame.Box)
        self.keyRightShift.setLineWidth(4)
        self.keyRightShift.setTextFormat(QtCore.Qt.AutoText)
        self.keyRightShift.setScaledContents(True)
        self.keyRightShift.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.keyRightShift.setObjectName("keyRightShift")
        self.keyTab = QtWidgets.QLabel(self.centralwidget)
        self.keyTab.setEnabled(True)
        self.keyTab.setGeometry(QtCore.QRect(235, 558, 118, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyTab.sizePolicy().hasHeightForWidth())
        self.keyTab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyTab.setFont(font)
        self.keyTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyTab.setMouseTracking(True)
        self.keyTab.setAutoFillBackground(False)
        self.keyTab.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyTab.setFrameShape(QtWidgets.QFrame.Box)
        self.keyTab.setLineWidth(4)
        self.keyTab.setTextFormat(QtCore.Qt.AutoText)
        self.keyTab.setScaledContents(True)
        self.keyTab.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.keyTab.setObjectName("keyTab")
        self.keyLeftShift = QtWidgets.QLabel(self.centralwidget)
        self.keyLeftShift.setEnabled(True)
        self.keyLeftShift.setGeometry(QtCore.QRect(235, 726, 184, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyLeftShift.sizePolicy().hasHeightForWidth())
        self.keyLeftShift.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyLeftShift.setFont(font)
        self.keyLeftShift.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyLeftShift.setMouseTracking(True)
        self.keyLeftShift.setAutoFillBackground(False)
        self.keyLeftShift.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyLeftShift.setFrameShape(QtWidgets.QFrame.Box)
        self.keyLeftShift.setLineWidth(4)
        self.keyLeftShift.setTextFormat(QtCore.Qt.AutoText)
        self.keyLeftShift.setScaledContents(True)
        self.keyLeftShift.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.keyLeftShift.setObjectName("keyLeftShift")
        self.keyFn = QtWidgets.QLabel(self.centralwidget)
        self.keyFn.setEnabled(True)
        self.keyFn.setGeometry(QtCore.QRect(235, 810, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyFn.sizePolicy().hasHeightForWidth())
        self.keyFn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyFn.setFont(font)
        self.keyFn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyFn.setMouseTracking(True)
        self.keyFn.setAutoFillBackground(False)
        self.keyFn.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyFn.setFrameShape(QtWidgets.QFrame.Box)
        self.keyFn.setLineWidth(4)
        self.keyFn.setTextFormat(QtCore.Qt.AutoText)
        self.keyFn.setScaledContents(True)
        self.keyFn.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.keyFn.setObjectName("keyFn")
        self.keyControl = QtWidgets.QLabel(self.centralwidget)
        self.keyControl.setEnabled(True)
        self.keyControl.setGeometry(QtCore.QRect(319, 810, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyControl.sizePolicy().hasHeightForWidth())
        self.keyControl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyControl.setFont(font)
        self.keyControl.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyControl.setMouseTracking(True)
        self.keyControl.setAutoFillBackground(False)
        self.keyControl.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyControl.setFrameShape(QtWidgets.QFrame.Box)
        self.keyControl.setLineWidth(4)
        self.keyControl.setTextFormat(QtCore.Qt.AutoText)
        self.keyControl.setScaledContents(True)
        self.keyControl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.keyControl.setObjectName("keyControl")
        self.keyLeftCommand = QtWidgets.QLabel(self.centralwidget)
        self.keyLeftCommand.setEnabled(True)
        self.keyLeftCommand.setGeometry(QtCore.QRect(487, 810, 100, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyLeftCommand.sizePolicy().hasHeightForWidth())
        self.keyLeftCommand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyLeftCommand.setFont(font)
        self.keyLeftCommand.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyLeftCommand.setMouseTracking(True)
        self.keyLeftCommand.setAutoFillBackground(False)
        self.keyLeftCommand.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyLeftCommand.setFrameShape(QtWidgets.QFrame.Box)
        self.keyLeftCommand.setLineWidth(4)
        self.keyLeftCommand.setTextFormat(QtCore.Qt.AutoText)
        self.keyLeftCommand.setScaledContents(True)
        self.keyLeftCommand.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.keyLeftCommand.setObjectName("keyLeftCommand")
        self.keyLeftOption = QtWidgets.QLabel(self.centralwidget)
        self.keyLeftOption.setEnabled(True)
        self.keyLeftOption.setGeometry(QtCore.QRect(403, 810, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyLeftOption.sizePolicy().hasHeightForWidth())
        self.keyLeftOption.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyLeftOption.setFont(font)
        self.keyLeftOption.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyLeftOption.setMouseTracking(True)
        self.keyLeftOption.setAutoFillBackground(False)
        self.keyLeftOption.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyLeftOption.setFrameShape(QtWidgets.QFrame.Box)
        self.keyLeftOption.setLineWidth(4)
        self.keyLeftOption.setTextFormat(QtCore.Qt.AutoText)
        self.keyLeftOption.setScaledContents(True)
        self.keyLeftOption.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.keyLeftOption.setObjectName("keyLeftOption")
        self.keyRightOption = QtWidgets.QLabel(self.centralwidget)
        self.keyRightOption.setEnabled(True)
        self.keyRightOption.setGeometry(QtCore.QRect(1115, 810, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyRightOption.sizePolicy().hasHeightForWidth())
        self.keyRightOption.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyRightOption.setFont(font)
        self.keyRightOption.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyRightOption.setMouseTracking(True)
        self.keyRightOption.setAutoFillBackground(False)
        self.keyRightOption.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyRightOption.setFrameShape(QtWidgets.QFrame.Box)
        self.keyRightOption.setLineWidth(4)
        self.keyRightOption.setTextFormat(QtCore.Qt.AutoText)
        self.keyRightOption.setScaledContents(True)
        self.keyRightOption.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.keyRightOption.setObjectName("keyRightOption")
        self.keyLeftArrow = QtWidgets.QLabel(self.centralwidget)
        self.keyLeftArrow.setEnabled(True)
        self.keyLeftArrow.setGeometry(QtCore.QRect(1199, 810, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyLeftArrow.sizePolicy().hasHeightForWidth())
        self.keyLeftArrow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyLeftArrow.setFont(font)
        self.keyLeftArrow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyLeftArrow.setMouseTracking(True)
        self.keyLeftArrow.setAutoFillBackground(False)
        self.keyLeftArrow.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyLeftArrow.setFrameShape(QtWidgets.QFrame.Box)
        self.keyLeftArrow.setLineWidth(4)
        self.keyLeftArrow.setTextFormat(QtCore.Qt.AutoText)
        self.keyLeftArrow.setScaledContents(True)
        self.keyLeftArrow.setAlignment(QtCore.Qt.AlignCenter)
        self.keyLeftArrow.setObjectName("keyLeftArrow")
        self.keyUpArrow = QtWidgets.QLabel(self.centralwidget)
        self.keyUpArrow.setEnabled(True)
        self.keyUpArrow.setGeometry(QtCore.QRect(1283, 810, 80, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyUpArrow.sizePolicy().hasHeightForWidth())
        self.keyUpArrow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyUpArrow.setFont(font)
        self.keyUpArrow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyUpArrow.setMouseTracking(True)
        self.keyUpArrow.setAutoFillBackground(False)
        self.keyUpArrow.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyUpArrow.setFrameShape(QtWidgets.QFrame.Box)
        self.keyUpArrow.setLineWidth(4)
        self.keyUpArrow.setTextFormat(QtCore.Qt.AutoText)
        self.keyUpArrow.setScaledContents(True)
        self.keyUpArrow.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.keyUpArrow.setObjectName("keyUpArrow")
        self.keyRightArrow = QtWidgets.QLabel(self.centralwidget)
        self.keyRightArrow.setEnabled(True)
        self.keyRightArrow.setGeometry(QtCore.QRect(1367, 810, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyRightArrow.sizePolicy().hasHeightForWidth())
        self.keyRightArrow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyRightArrow.setFont(font)
        self.keyRightArrow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyRightArrow.setMouseTracking(True)
        self.keyRightArrow.setAutoFillBackground(False)
        self.keyRightArrow.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyRightArrow.setFrameShape(QtWidgets.QFrame.Box)
        self.keyRightArrow.setLineWidth(4)
        self.keyRightArrow.setTextFormat(QtCore.Qt.AutoText)
        self.keyRightArrow.setScaledContents(True)
        self.keyRightArrow.setAlignment(QtCore.Qt.AlignCenter)
        self.keyRightArrow.setObjectName("keyRightArrow")
        self.keyDownArrow = QtWidgets.QLabel(self.centralwidget)
        self.keyDownArrow.setEnabled(True)
        self.keyDownArrow.setGeometry(QtCore.QRect(1283, 850, 80, 39))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyDownArrow.sizePolicy().hasHeightForWidth())
        self.keyDownArrow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyDownArrow.setFont(font)
        self.keyDownArrow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyDownArrow.setMouseTracking(True)
        self.keyDownArrow.setAutoFillBackground(False)
        self.keyDownArrow.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyDownArrow.setFrameShape(QtWidgets.QFrame.Box)
        self.keyDownArrow.setLineWidth(4)
        self.keyDownArrow.setTextFormat(QtCore.Qt.AutoText)
        self.keyDownArrow.setScaledContents(True)
        self.keyDownArrow.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.keyDownArrow.setObjectName("keyDownArrow")
        self.keyRightCommand = QtWidgets.QLabel(self.centralwidget)
        self.keyRightCommand.setEnabled(True)
        self.keyRightCommand.setGeometry(QtCore.QRect(1011, 810, 100, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyRightCommand.sizePolicy().hasHeightForWidth())
        self.keyRightCommand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyRightCommand.setFont(font)
        self.keyRightCommand.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyRightCommand.setMouseTracking(True)
        self.keyRightCommand.setAutoFillBackground(False)
        self.keyRightCommand.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.keyRightCommand.setFrameShape(QtWidgets.QFrame.Box)
        self.keyRightCommand.setLineWidth(4)
        self.keyRightCommand.setTextFormat(QtCore.Qt.AutoText)
        self.keyRightCommand.setScaledContents(True)
        self.keyRightCommand.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.keyRightCommand.setObjectName("keyRightCommand")
        self.keyBackslash = QtWidgets.QLabel(self.centralwidget)
        self.keyBackslash.setEnabled(True)
        self.keyBackslash.setGeometry(QtCore.QRect(1367, 558, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.keyBackslash.sizePolicy().hasHeightForWidth())
        self.keyBackslash.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyBackslash.setFont(font)
        self.keyBackslash.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keyBackslash.setMouseTracking(True)
        self.keyBackslash.setAutoFillBackground(False)
        self.keyBackslash.setStyleSheet("background-color: rgba(146, 223, 174, 255); color: rgba(112, 132, 119, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: rgba(112, 132, 119, 255);\n"
"border-width: 4px;\n"
"")
        self.keyBackslash.setFrameShape(QtWidgets.QFrame.Box)
        self.keyBackslash.setLineWidth(4)
        self.keyBackslash.setTextFormat(QtCore.Qt.AutoText)
        self.keyBackslash.setScaledContents(True)
        self.keyBackslash.setAlignment(QtCore.Qt.AlignCenter)
        self.keyBackslash.setObjectName("keyBackslash")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 522, 1640, 5))
        self.progressBar.setStyleSheet("QProgressBar::chunk {background-color: rgba(255, 255, 255, 170);; width: 1px; margin: 0px;} \n"
"QProgressBar {background-color: rgba(0, 0, 0, 20); border: 0px solid; border-radius: 5px; text-align: center;}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.graphWidget = PlotWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(594, 208, 503, 223))
        self.graphWidget.setStyleSheet("")
        self.graphWidget.setObjectName("graphWidget")
        self.finished = QtWidgets.QLabel(self.centralwidget)
        self.finished.setGeometry(QtCore.QRect(1150, 100, 400, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.finished.sizePolicy().hasHeightForWidth())
        self.finished.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.finished.setFont(font)
        self.finished.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.finished.setMouseTracking(True)
        self.finished.setAutoFillBackground(False)
        self.finished.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 4px;")
        self.finished.setFrameShape(QtWidgets.QFrame.Box)
        self.finished.setLineWidth(4)
        self.finished.setTextFormat(QtCore.Qt.AutoText)
        self.finished.setScaledContents(True)
        self.finished.setAlignment(QtCore.Qt.AlignCenter)
        self.finished.setObjectName("finished")
        self.textField = QtWidgets.QTextEdit(self.centralwidget)
        self.textField.setEnabled(False)
        self.textField.setGeometry(QtCore.QRect(838, 437, 842, 85))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(60)
        self.textField.setFont(font)
        self.textField.setStyleSheet("background-color: rgba(255, 255, 255, 0); color: rgba(255, 255, 255, 255);\n"
"")
        self.textField.setTabChangesFocus(True)
        self.textField.setUndoRedoEnabled(False)
        self.textField.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textField.setCursorWidth(0)
        self.textField.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.textField.setObjectName("textField")
        self.askForLayoutSwitch = QtWidgets.QLabel(self.centralwidget)
        self.askForLayoutSwitch.setGeometry(QtCore.QRect(539, 230, 611, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.askForLayoutSwitch.sizePolicy().hasHeightForWidth())
        self.askForLayoutSwitch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.askForLayoutSwitch.setFont(font)
        self.askForLayoutSwitch.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.askForLayoutSwitch.setMouseTracking(True)
        self.askForLayoutSwitch.setAutoFillBackground(False)
        self.askForLayoutSwitch.setStyleSheet("background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);")
        self.askForLayoutSwitch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.askForLayoutSwitch.setLineWidth(4)
        self.askForLayoutSwitch.setTextFormat(QtCore.Qt.AutoText)
        self.askForLayoutSwitch.setScaledContents(True)
        self.askForLayoutSwitch.setAlignment(QtCore.Qt.AlignCenter)
        self.askForLayoutSwitch.setObjectName("askForLayoutSwitch")
        self.username = QtWidgets.QPushButton(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(0, 910, 1680, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(60)
        self.username.setFont(font)
        self.username.setStyleSheet("QPushButton {background-color: rgba(0, 0, 0, 0); color: rgba(255, 255, 255, 255);}\n"
"QPushButton::hover::!pressed {background-color: rgba(0, 0, 0, 0); color: rgba(255, 255, 255, 255);}\n"
"")
        self.username.setObjectName("username")
        self.pastResultsButton = QtWidgets.QPushButton(self.centralwidget)
        self.pastResultsButton.setGeometry(QtCore.QRect(655, 36, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pastResultsButton.setFont(font)
        self.pastResultsButton.setStyleSheet("QPushButton {background-color: rgba(32, 32, 32, 0); color: rgba(255, 255, 255, 100);\n"
"border-radius: 20px;\n"
"border-style: solid;\n"
"border-color: rgba(159, 208, 255, 255);\n"
"border-width: 0px;}\n"
"QPushButton::hover::!pressed {background-color: rgba(20, 25, 80, 0); color: rgba(255, 255, 255, 255); border-color: rgba(255, 255, 255, 255)}\n"
"QPushButton::pressed {background-color: rgba(255, 255, 255, 255)};")
        self.pastResultsButton.setCheckable(False)
        self.pastResultsButton.setChecked(False)
        self.pastResultsButton.setFlat(False)
        self.pastResultsButton.setObjectName("pastResultsButton")
        self.graphWidget.raise_()
        self.askForLayoutSwitch.raise_()
        self.finished.raise_()
        self.textField.raise_()
        self.stopwatch.raise_()
        self.pause.raise_()
        self.typingSpeed.raise_()
        self.mistakesMade.raise_()
        self.insert.raise_()
        self.keyO.raise_()
        self.keyT.raise_()
        self.keySpace.raise_()
        self.keyI.raise_()
        self.keyG.raise_()
        self.keyD.raise_()
        self.keyR.raise_()
        self.keyC.raise_()
        self.keyH.raise_()
        self.keyV.raise_()
        self.keyP.raise_()
        self.keyQ.raise_()
        self.keyW.raise_()
        self.keyN.raise_()
        self.keyY.raise_()
        self.keyS.raise_()
        self.keyB.raise_()
        self.keyL.raise_()
        self.keyJ.raise_()
        self.keyF.raise_()
        self.keyE.raise_()
        self.keyU.raise_()
        self.keyX.raise_()
        self.keyM.raise_()
        self.keyA.raise_()
        self.keyK.raise_()
        self.keyZ.raise_()
        self.keyDot.raise_()
        self.keyComma.raise_()
        self.keySemicolon.raise_()
        self.keyQuote.raise_()
        self.keyLeftBracket.raise_()
        self.keyRightBracket.raise_()
        self.keyCaps.raise_()
        self.keyReturn.raise_()
        self.keySlash.raise_()
        self.keyRightShift.raise_()
        self.keyTab.raise_()
        self.keyLeftShift.raise_()
        self.keyFn.raise_()
        self.keyControl.raise_()
        self.keyLeftCommand.raise_()
        self.keyLeftOption.raise_()
        self.keyRightOption.raise_()
        self.keyLeftArrow.raise_()
        self.keyUpArrow.raise_()
        self.keyRightArrow.raise_()
        self.keyDownArrow.raise_()
        self.keyRightCommand.raise_()
        self.keyBackslash.raise_()
        self.progressBar.raise_()
        self.username.raise_()
        self.pastResultsButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.keyQ.setText(_translate("MainWindow", "Q"))
        self.keyW.setText(_translate("MainWindow", "W"))
        self.keyE.setText(_translate("MainWindow", "E"))
        self.keyR.setText(_translate("MainWindow", "R"))
        self.keyT.setText(_translate("MainWindow", "T"))
        self.keyI.setText(_translate("MainWindow", "I"))
        self.keyU.setText(_translate("MainWindow", "U"))
        self.keyY.setText(_translate("MainWindow", "Y"))
        self.keyO.setText(_translate("MainWindow", "O"))
        self.keyP.setText(_translate("MainWindow", "P"))
        self.keyK.setText(_translate("MainWindow", "K"))
        self.keyH.setText(_translate("MainWindow", "H"))
        self.keyA.setText(_translate("MainWindow", "A"))
        self.keyF.setText(_translate("MainWindow", "F"))
        self.keyL.setText(_translate("MainWindow", "L"))
        self.keyJ.setText(_translate("MainWindow", "J"))
        self.keyD.setText(_translate("MainWindow", "D"))
        self.keyS.setText(_translate("MainWindow", "S"))
        self.keyG.setText(_translate("MainWindow", "G"))
        self.keyN.setText(_translate("MainWindow", "N"))
        self.keyZ.setText(_translate("MainWindow", "Z"))
        self.keyV.setText(_translate("MainWindow", "V"))
        self.keyM.setText(_translate("MainWindow", "M"))
        self.keyC.setText(_translate("MainWindow", "C"))
        self.keyX.setText(_translate("MainWindow", "X"))
        self.keyB.setText(_translate("MainWindow", "B"))
        self.stopwatch.setText(_translate("MainWindow", "0"))
        self.pause.setText(_translate("MainWindow", "PAUSED"))
        self.typingSpeed.setText(_translate("MainWindow", "0cpm"))
        self.insert.setText(_translate("MainWindow", "|"))
        self.mistakesMade.setText(_translate("MainWindow", "Mistakes: 0"))
        self.keyDot.setText(_translate("MainWindow", ". >"))
        self.keyComma.setText(_translate("MainWindow", ", <"))
        self.keySemicolon.setText(_translate("MainWindow", "; :"))
        self.keyQuote.setText(_translate("MainWindow", "\' \""))
        self.keyLeftBracket.setText(_translate("MainWindow", "[ {"))
        self.keyRightBracket.setText(_translate("MainWindow", "] }"))
        self.keyCaps.setText(_translate("MainWindow", "caps lock"))
        self.keyReturn.setText(_translate("MainWindow", "return"))
        self.keySlash.setText(_translate("MainWindow", "/ ?"))
        self.keyRightShift.setText(_translate("MainWindow", "shift"))
        self.keyTab.setText(_translate("MainWindow", "tab"))
        self.keyLeftShift.setText(_translate("MainWindow", "shift"))
        self.keyFn.setText(_translate("MainWindow", "fn"))
        self.keyControl.setText(_translate("MainWindow", "control"))
        self.keyLeftCommand.setText(_translate("MainWindow", "command"))
        self.keyLeftOption.setText(_translate("MainWindow", "option"))
        self.keyRightOption.setText(_translate("MainWindow", "option"))
        self.keyLeftArrow.setText(_translate("MainWindow", "◀︎"))
        self.keyUpArrow.setText(_translate("MainWindow", "▲"))
        self.keyRightArrow.setText(_translate("MainWindow", "►"))
        self.keyDownArrow.setText(_translate("MainWindow", "▼"))
        self.keyRightCommand.setText(_translate("MainWindow", "command"))
        self.keyBackslash.setText(_translate("MainWindow", "\\ |"))
        self.finished.setText(_translate("MainWindow", "FINISHED"))
        self.textField.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica Neue\'; font-size:60pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">y</span></p></body></html>"))
        self.askForLayoutSwitch.setText(_translate("MainWindow", "Switch layout!"))
        self.username.setText(_translate("MainWindow", "Username"))
        self.pastResultsButton.setText(_translate("MainWindow", "Past Results"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
