"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['typist.py']
DATA_FILES = [('lessons', ['lessons/test_lesson.txt', 'lessons/user_lesson0.txt', 'lessons/user_lesson1.txt']),
              'session_history.json', 'choose_lesson.py', 'greeting.py', 'main_interface.py', 'new_lesson.py',
              'past_sessions.py', 'lessons.json']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'PyQt5==5.13', 'pyqtgraph'],
)
